app = "icp-proxy"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[experimental]
  cmd = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]